export const ENV_VARS = {
  APP_CACHE_PREFIX: "APP_CACHE_PREFIX",
  REDIS_HOST: "REDIS_HOST",
  REDIS_PORT: "REDIS_PORT",
  REDIS_PASSWORD: "REDIS_PASSWORD",
  CACHE_TTL: "CACHE_TTL",
  DATABASE_URL: "DATABASE_URL",
  MAIN_APP_PORT: "MAIN_APP_PORT",
  AGENT_SCHEDULE_PORT: "AGENT_SCHEDULE_PORT",
  CONVERSATION_SKILL_MAPPER_APP_PORT: "CONVERSATION_SKILL_MAPPER_APP_PORT",
  CONVERSATION_AUTO_END_APP_PORT: "CONVERSATION_AUTO_END_APP_PORT",
  AGENT_ONLINE_TRACKING_APP_PORT: "AGENT_ONLINE_TRACKING_APP_PORT",

  SMOOCH_URL_V2: "SMOOCH_URL_V2",
  SMOOCH_APP_ID: "SMOOCH_APP_ID",
  WABA_URL: "WABA_URL",
  AUDIO_TRANSCRIPT_URL: "AUDIO_TRANSCRIPT_URL",
  AUDIO_TRANSCRIPT_API_KEY: "AUDIO_TRANSCRIPT_API_KEY",
  ZALO_OUTBOUND_URL: "ZALO_OUTBOUND_URL",
  FACEBOOK_FEED_GRAPH_URL: "FACEBOOK_FEED_GRAPH_URL",
  INSTAGRAM_POST_GRAPH_URL: "INSTAGRAM_POST_GRAPH_URL",
  TWITTER_SERVICE_URL: "TWITTER_SERVICE_URL",
  FB_IG_WEBHOOK_VERIFY_TOKEN: "FB_IG_WEBHOOK_VERIFY_TOKEN",
  SUPERVISOR_URL: "SUPERVISOR_URL",
  MICROTEL_CHATBOT_URL: "MICROTEL_CHATBOT_URL",
  GENERATE_WEB_API_CREDENTIAL_ID: "GENERATE_WEB_API_CREDENTIAL_ID",
  JWT_SECRET: "JWT_SECRET",
  JWT_SECRET_AGENT_CX: "JWT_SECRET_AGENT_CX",
  DIALOGFLOW_PROJECT_ID: "DIALOGFLOW_PROJECT_ID",
  COLLAB_END_CHAT_MESSAGE: "COLLAB_END_CHAT_MESSAGE",
  COLLAB_ACCEPTED_CHAT_MESSAGE: "COLLAB_ACCEPTED_CHAT_MESSAGE",
  ENVIRONMENT_MIDDLEWARE: "ENVIRONMENT_MIDDLEWARE",
  AGENT_OFFLINE_AFTER_LOST_CONNECT_IN_SECONDS:
    "AGENT_OFFLINE_AFTER_LOST_CONNECT_IN_SECONDS",

  CLICK_TO_CHAT_AUTH_DISABLED: "CLICK_TO_CHAT_AUTH_DISABLED",
  JWT_CLICK_TO_CHAT_SECRET: "JWT_CLICK_TO_CHAT_SECRET",
};

export const envFilePath =
  process.env.NODE_ENV && process.env.NODE_ENV !== "dev"
    ? `${process.cwd()}/.env.${process.env.NODE_ENV}`
    : `${process.cwd()}/.env`;

// v_call_center_queues_channels
export const CHANNEL_IDS = {
  CHAT: 2,
  EMAIL: 3,
  SOCIAL_POST: 5,
};

export const INSTAGRAM_REELS = {
  INITIAL_WAIT: 10000,
  RETRY_INTERVAL: 10000,
  MAX_RETRIES: 5,
} as const;

export const SKILL_ID_NONE = "none";
export const POST_SENDER_MENTION = "@sender";
export const ERROR_NEW_EXISTING_RECORD = 201;
// make sure check after agent socket message
export const ADDITIONAL_MILLISECONDS__CHECK_WRAP_UP_AFTER_END = 5000;
export const AUTO_REPLY_MESSAGE_BREAK = "<MESSAGE_BREAK>";

export const CUSTOMER_LEFT_MESSAGE =
  "Customer left the chat, please end the chat";
export const WEBHOOK_TIME_THRESHOLD = 15; // 15 seconds threshold
